### ISSUE TITLE
cross browser

### ISSUE THREAD

**Issue by millykat** [bcko/Ud-FrontEnd-MemoryGame#1]
Hi,
 is there a version that can also work on ie?

**Comment by bcko** [comment]
Hello @millykat 
the project is written using Javascript features not available on IE. However, you can transpile the JS code so that it can work on IE using BabelJS(https://babeljs.io/).
Let me know if that works!

**Comment by millykat** [comment]
Yes @bcko now it works in IE !
Only some minor css issues. Thank you!
